language: cpp

os: linux

compiler:
  - clang
  - gcc

env:
  - CHECKED=no
  - CHECKED=yes

install:
  - sudo cpanm File::Slurp Digest::MD5

script:
  - make NO_GIT_FILE=1 all run-all-tests
  - make NO_GIT_FILE=1 CROSSMINGW=yes all

addons:
  apt:
    packages:
      valgrind
      yasm
      cpanminus
      mingw-w64
      g++-mingw-w64-x86-64
