language: cpp

os: linux

compiler:
  - clang
  - gcc

env:
  - CHECKED=no
  - CHECKED=yes

script:
  - make NO_GIT_FILE=1 all run-test

  # This needs some more work
  #- perl run-tests.pl $(BUILD_DIR)/tundra2

addons:
  apt:
    packages:
      valgrind
