language: cpp

os: linux

compiler:
  - clang
  - gcc

env:
  - CHECKED=no
  - CHECKED=yes

script:
  - sudo cpanm File::Slurp Digest::MD5
  - make NO_GIT_FILE=1 all run-all-tests

addons:
  apt:
    packages:
      valgrind
      yasm
      cpanminus
